#!/bin/bash

function datediff () {
	a=$(date --date=@"$1" +%s)
	b=$(date --date=@"$2" +%s)
	echo $(( (b - a) ))
}

function showtime () {
	h=$(echo "${1}/3600" | bc)
	m=$(echo "(${1}%3600)/60" | bc)
	s=$(echo "${1}%60" | bc)

	line=''
	if [ "$h" -ne 0 ]; then
		line+=$(printf '%dh' "$h")
	fi
	if [ "$m" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%dm' "$m")
	fi
	if [ "$s" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%ds' "$s")
	fi
	echo "$line"
}

timedir="$TIMEUPDIR"
if [ -z "$timedir" ]; then
	timedir="$HOME/.timeup"
	if [ ! -d "$timedir" ]; then
		read -rp "Create $timedir? (y/N)? " ans
		if [[ $ans =~ ^[Yy]$ ]]
			exit
		then
			mkdir "$timedir"
			mkdir "$timedir/projects"
		fi
	fi
fi

histfile="$timedir/history.txt"
lockfile="$timedir/.lock"
projdir="$timedir/projects"
utc=$(date +'%s')

if [ -f "$lockfile" ]; then
	task=$(<"$lockfile" cut -d ' ' -f1)
	since=$(<"$lockfile" cut -d ' ' -f2)
	diff=$(datediff "$since" "$utc")
	duration=$(showtime "$diff")
	nbsp='<i> </i>'
	notify-send -u critical -t 4000 "$nbsp$task stopped ($duration)"
	echo "$task $since $utc" >> "$histfile"
	rm "$lockfile"
fi

task=$(find "$projdir" -mindepth 2 -printf '%P\n' \
	| cat - "$histfile" \
	| cut -d ' ' -f1 \
	| sort \
	| uniq --count \
	| sort -k1,1nr -k2,2 \
	| colrm 1 8 \
	| dmenu -sb '#aa0000' "$@" )

if [ -z "$task" ]; then
	exit 0
fi

nbsp='<i> </i>'
notify-send "$nbsp$task started"
echo "$task $utc" > "$lockfile"
