#!/bin/bash -e

function datediff () {
	a=$(date --date=@"$1" +%s)
	b=$(date --date=@"$2" +%s)
	echo $(( (b - a) ))
}

function showtime () {
	h=$(echo "$1/3600" | bc)
	m=$(echo "($1%3600)/60" | bc)
	s=$(echo "$1%60" | bc)

	line=''
	if [ "$h" -ne 0 ]; then
		line+=$(printf '%dh' "$h")
	fi
	if [ "$m" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%dm' "$m")
	fi
	if [ "$s" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%ds' "$s")
	fi
	echo "$line"
}

utc=$(date +'%s')
timedir="$TIMEUPDIR"
if [ -z "$timedir" ]; then
	timedir="$HOME/.timeup"
	if [ ! -d "$timedir" ]; then
		read -rp "Create $timedir? (y/N)? " ans
		if [[ $ans =~ ^[Yy]$ ]]; then
			exit
		else
			mkdir -p "$timedir"
		fi
	fi
fi

archivefile="$timedir/archived.txt"
histfile="$timedir/history.txt"
lockfile="$timedir/.lock"

# filters
task=''
minutc=0
maxutc=4131262800 # 2100-12-1

function track () {
	diff=$(datediff "$2" "$3")
	duration=$(showtime "$diff")
	notify-send -u critical -t 4000 '' "$1 ($duration)"
	echo "logged $1 ($duration)"
	echo "$1 $2 $3" >> "$histfile"
}

function comment () {
	_task_=$(echo -n "$1" | sed 's/\//_/g')
	_file="$timedir/comments/""$_task_""_$2"
	st -e "$EDITOR" "$_file"
	if [ ! -s "$_file" ]; then
		rm --force "$_file"
	fi
}

function uncomment () {
	_task_=$(echo -n "$1" | sed 's/\//_/g')
	_file="$timedir/comments/""$_task_""_$2"
	if [ -f "$_file" ]; then
		rm "$_file"
	fi
}

function mvcomment () {
	_task_=$(echo -n "$1" | sed 's/\//_/g')
	_file="$timedir/comments/""$_task_""_$2"
	if [ -f "$_file" ]; then
		mv "$_file" "$timedir/comments/""$_task_""_$3"
	fi
}

function endtask () {
	_task=$(<"$lockfile" cut -f1 -d' ')
	_since=$(<"$lockfile" cut -f2 -d' ')
	track "$_task" "$_since" "$utc"
	rm "$lockfile"
}

pyfilter=$(cat << END
import sys

wanted = sys.argv[1]
minutc = int(sys.argv[2])
maxutc = int(sys.argv[3])
match = sys.argv[4] == 'match'
for line in sys.stdin:
	(task, begin, end) = line.split(' ', 2)
	if (match and task.count(wanted) > 0 and int(begin) >= minutc and int(end) <= maxutc):
		sys.stdout.write(line)
	elif (not match):
		sys.stdout.write(line)
END
)

function archivetask () {
	bak=$(mktemp)
	<"$histfile" python -c "$pyfilter" "$3" "$1" "$2" match >> "$archivefile"
	<"$histfile" python -c "$pyfilter" "$3" "$1" "$2" drop > "$bak"
	count=$(<"$histfile" python -c "$pyfilter" "$3" "$1" "$1" match | wc -l)
	echo "archived $1 ($count entries)"
	mv "$bak" "$histfile"
}

function starttask () {
	if [ -f "$lockfile" ]; then
		endtask
	fi

	notify-send '' "$1 started"
	echo "$1 $utc" > "$lockfile"
}

# shellcheck disable=SC2059
function report () {
	pymap=$(cat << END
from collections import Counter
import sys

minutc = int(sys.argv[1])
maxutc = int(sys.argv[2])
sum = 0
durations = Counter()
count = Counter()
for line in sys.stdin:
	(task, begin, end) = line.split(' ', 2)
	begin = int(begin)
	end = int(end)
	if (begin < minutc): continue
	if (end > maxutc): continue

	duration = end - begin
	durations[task] += duration
	count[task] += 1
	durations['Total'] += duration
	count['Total'] += 1

report = sorted((x, durations[x]) for x in durations)
for a, b in report:
	if (a == 'Total'): continue
	print(a, count[a], b)

print()
print('Total', count['Total'], durations['Total'])
END
	)

	_format='%-24s %-14s %-5s\n'
	if [ -n "$3" ]; then
		printf "$_format" "Task ($3)" 'Duration' 'Count'
	else
		printf "$_format" 'Task' 'Duration' 'Count'
	fi
	printf "$_format" '------------------------' '--------------' '-----'
	{
		if [ -n "$3" ]; then
			<"$histfile" grep "^$3[ /]"
			[ -n "$4" ] && <"$archivefile" grep "^$3[ /]"
		else
			cat "$histfile"
			[ -n "$4" ] && cat "$archivefile"
		fi
	} | python -c "$pymap" "$1" "$2" | while read -r line; do
		if [ -z "$line" ]; then
			printf "$_format" '------------------------' '--------------' '-----'
			continue
		fi
		_task=$(echo "$line" | cut -f1 -d' ')
		_instances=$(echo "$line" | cut -f2 -d' ')
		_seconds=$(echo "$line" | cut -f3 -d' ')
		duration=$(showtime "$_seconds")
		printf "$_format" "$_task" "$duration" "$_instances"
	done
}

# boo, poor performance
function log () {
	_a=$(date --date=@"$2" +"%a %H:%M %d/%m")
	_b=$(date --date=@"$3" +"%a %H:%M %d/%m")
	diff=$(datediff "$2" "$3")
	duration=$(showtime "$diff")
	_task=$(echo -n "$1" | sed 's/\//_/g')
	_file="$timedir/comments/""$_task""_$2_$3"
	echo "$1, $_a to $_b for $duration"
	if [ -f "$_file" ]; then
		<"$_file" sed 's/^/	/g'
	fi
}

function logrange () {
	{
		<"$histfile" python -c "$pyfilter" "$3" "$1" "$2" match
	} | while read -r line; do
		_task=$(echo "$line" | cut -f1 -d' ')
		_utc1=$(echo "$line" | cut -f2 -d' ')
		_utc2=$(echo "$line" | cut -f3 -d' ')
		log "$_task" "$_utc1" "$_utc2"
	done
}

if [ "$1" == 'stop' ]; then
	if [ -f "$lockfile" ]; then
		endtask
	fi

	exit 0
fi

if [ "$1" == 'last' ]; then
	line=$(<"$histfile" tail -n1)
	_task=$(echo "$line" | cut -f1 -d' ')
	_utc1=$(echo "$line" | cut -f2 -d' ')
	_utc2=$(echo "$line" | cut -f3 -d' ')
	log "$_task" "$_utc1" "$_utc2"
	exit 0
fi

if [ "$1" == 'track' ]; then
	if [ "$#" -eq 3 ]; then
		minutc=$(date --date="now-$3" +%s)
		maxutc="$utc"
	elif [ "$#" -eq 4 ]; then
		minutc=$(date --date="$3" +%s)
		maxutc=$(date --date="$4" +%s)
	else
		echo 'Invalid arguments'
		exit 1
	fi

	track "$2" "$minutc" "$maxutc"
	exit 0
fi

if [ "$1" == 'archive' ]; then
	if [ "$#" -eq 2 ]; then
		minutc=$(date --date="last year" +%s)
	elif [ "$#" -eq 3 ]; then
		minutc=$(date --date="last year" +%s)
		maxutc=$(date --date="$3" +%s)
	elif [ "$#" -eq 4 ]; then
		minutc=$(date --date="$3" +%s)
		maxutc=$(date --date="$4" +%s)
	else
		echo 'Invalid arguments'
		exit 1
	fi

	archivetask "$minutc" "$maxutc" "$2"
	exit 0
fi

if [ "$1" == 'report' ] || [ "$1" == 'areport' ] || [ "$1" == "log" ]; then
	# date to date
	if [ "$#" -gt 2 ]; then
		minutc=$(date --date="$2" +%s)
		maxutc=$(date --date="$3" +%s)
	# 1 day
	elif [ "$#" -gt 1 ]; then
		minutc="$2"
		if [ "$2" == "today" ]; then
			minutc="0:00"
		fi

		minutc=$(date --date="$minutc" +%s 2> /dev/null)
		if [ -z "$minutc" ]; then
			minutc=0
			task="$2"
		else
			maxutc=$(echo "$minutc+86400" | bc)
		fi
	fi

	# support task filtering
	if [ "$#" -gt 3 ]; then
		task="$4"
	fi

	if [ "$1" == 'areport' ]; then
		report "$minutc" "$maxutc" "$task" archive
	elif [ "$1" == 'report' ]; then
		report "$minutc" "$maxutc" "$task"
	else
		logrange "$minutc" "$maxutc" "$task"
	fi
	exit 0
fi

if [ "$1" == 'drop' ]; then
	line=$(<"$histfile" tail -n1)
	_task=$(echo "$line" | cut -f1 -d' ')
	_utc1=$(echo "$line" | cut -f2 -d' ')
	_utc2=$(echo "$line" | cut -f3 -d' ')
	diff=$(datediff "$_utc1" "$_utc2")
	duration=$(showtime "$diff")

	sed -i '$ d' "$histfile"
	uncomment "$_task" "$_utc1"
	notify-send -u critical -t 4000 '' "Dropped $_task ($duration)"
	exit 1
fi

if [ "$1" == 'edit' ]; then
	line=$(<"$histfile" tail -n1)
	_task=$(echo "$line" | cut -f1 -d' ')
	_utc1=$(echo "$line" | cut -f2 -d' ')
	_utc2=$(echo "$line" | cut -f3 -d' ')

	if [ "$#" -eq 2 ]; then
		tmp=$(date --date=@"$_utc2")
		a=$(date --date="$tmp-$2" +%s)
		b="$_utc2"
	elif [ "$#" -eq 3 ]; then
		a=$(date --date="$2" +%s)
		b=$(date --date="$3" +%s)
	else
		echo 'Invalid arguments'
		exit 1
	fi

	sed -i '$ d' "$histfile"
	mvcomment "$_task" "$_utc1" "$_a"
	track "$_task" "$a" "$b"
	exit 0
fi

if [ "$1" == 'comment' ]; then
	if [ -f "$lockfile" ]; then
		_task=$(<"$lockfile" cut -f1 -d' ')
		_utc1=$(<"$lockfile" cut -f2 -d' ')
	else
		line=$(<"$histfile" tail -n1)
		_task=$(echo "$line" | cut -f1 -d' ')
		_utc1=$(echo "$line" | cut -f2 -d' ')
	fi

	comment "$_task" "$_utc1"
	exit 0
fi

task=$( \
	{ \
		yes "$(<"$histfile" tail -n1)" | head -n4 # previous
		yes "$(<"$histfile" tail -n3)" | head -n3 # previous 3
		<"$histfile" tail -n5 # recent 5
		<"$histfile" tail -n50 | cut -f1 -d' ' | sort --unique # recent 50
		<"$histfile" tail -n100 | cut -f1 -d' ' | sort --unique # recent 100
	} | cut -f1 -d' ' \
	| sort \
	| uniq --count \
	| sort -k1,1nr -k2,2 \
	| colrm 1 8 \
	| dmenu "$@")

if [ -z "$task" ]; then
	exit 0
fi

starttask "$task"
