#!/bin/bash

function datediff () {
	a=$(date --date=@"$1" +%s)
	b=$(date --date=@"$2" +%s)
	echo $(( (b - a) ))
}

function showtime () {
	h=$(echo "${1}/3600" | bc)
	m=$(echo "(${1}%3600)/60" | bc)
	s=$(echo "${1}%60" | bc)

	line=''
	if [ "$h" -ne 0 ]; then
		line+=$(printf '%02dh' "$h")
	fi
	if [ "$m" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%02dm' "$m")
	fi
	if [ "$s" -ne 0 ]; then
		line+=$([[ -n $line ]] && echo ' ')
		line+=$(printf '%02ds' "$s")
	fi
	echo "$line"
}

timedir="$TIMEUPDIR"
if [ -z "$timedir" ]; then
	timedir="$HOME/.timeup"
	if [ ! -d "$timedir" ]; then
		read -p "Create new database in $timedir? (yes/no)? " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]
			mkdir "$timedir"
		then
			exit
		fi
	fi
fi

histfile="$timedir/history.txt"
lockfile="$timedir/.lock"
utc=$(date +'%s')

if [ -f "$lockfile" ]; then
	task=$(<"$lockfile" cut -d ' ' -f1)
	since=$(<"$lockfile" cut -d ' ' -f2)
	diff=$(datediff "$since" "$utc")
	duration=$(showtime "$diff")
	nbsp='<i> </i>'
	notify-send -u critical "$nbsp$task stopped ($duration)"
	{
		echo "$task $since $utc"
	} > "$histfile"
	rm "$lockfile"

else
	tasks=$(find "$timedir/projects" -mindepth 2 -printf '%P\n')
	last20=$(<"$histfile" tail -n100 | cut -d ' ' -f1)
	task=$(echo "$tasks" "$last20" \
		| sort \
		| uniq --count \
		| sort -k1,1nr -k2,2 \
		| colrm 1 8 \
		| dmenu "$@" \
		| tee -a "$histfile")

	if [ -z "$task" ]; then
		exit 0
	fi

	nbsp='<i> </i>'
	notify-send "$nbsp$task"
	{
		echo "$task $utc"
	} > "$lockfile"
fi
