#!/bin/python

import csv
import datetime
import sys

def asutc (d):
    return int(d.timestamp())

reader = csv.DictReader(sys.stdin, delimiter=',')
for row in reader:
    date = row['Date']
    hours = row['Hours']

    client = row['Client']
    project = row['Project']
    task = row['Task']

    date = datetime.datetime.strptime(date, "%Y-%m-%d")
    hours = datetime.timedelta(hours=float(hours))

    task = '/'.join(x for x in (client, project, task) if len(x) > 0).lower()
    start = date
    end = date + hours
    print(task, asutc(start), asutc(end))
